// <auto-generated />
using System;
using EquipmentMonitoring.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentMonitoring.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutomationDeviceUnit", b =>
                {
                    b.Property<Guid>("AutomationDevicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitsId")
                        .HasColumnType("uuid");

                    b.HasKey("AutomationDevicesId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("AutomationDeviceUnit");
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.AutomationDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AutomationDevices", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActiveOperationId");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Variables", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Records.EquipmentStateChangeRecord", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurringTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewState")
                        .HasColumnType("integer");

                    b.HasKey("EquipmentId", "OccurringTime");

                    b.ToTable("StateChangeRecords", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.HMI", b =>
                {
                    b.HasBaseType("EquipmentMonitoring.Domain.Entities.AutomationDevice");

                    b.ToTable("HMIs", (string)null);
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.PLC", b =>
                {
                    b.HasBaseType("EquipmentMonitoring.Domain.Entities.AutomationDevice");

                    b.ToTable("PLCs", (string)null);
                });

            modelBuilder.Entity("AutomationDeviceUnit", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.AutomationDevice", null)
                        .WithMany()
                        .HasForeignKey("AutomationDevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentMonitoring.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.AutomationDevice", b =>
                {
                    b.OwnsOne("EquipmentMonitoring.Domain.ValueObjects.NetworkAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("AutomationDeviceId")
                                .HasColumnType("uuid");

                            b1.HasKey("AutomationDeviceId");

                            b1.ToTable("AutomationDevices");

                            b1.WithOwner()
                                .HasForeignKey("AutomationDeviceId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Operation", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.Unit", null)
                        .WithMany("Operations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Unit", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.Operation", "ActiveOperation")
                        .WithMany()
                        .HasForeignKey("ActiveOperationId");

                    b.OwnsOne("EquipmentMonitoring.Domain.ValueObjects.UnitIdentificationCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("ActiveOperation");

                    b.Navigation("Code")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Variable", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.Unit", null)
                        .WithMany("Variables")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EquipmentMonitoring.Domain.ValueObjects.CommunicationNode", "ValueNode", b1 =>
                        {
                            b1.Property<Guid>("VariableId")
                                .HasColumnType("uuid");

                            b1.HasKey("VariableId");

                            b1.ToTable("Variables");

                            b1.WithOwner()
                                .HasForeignKey("VariableId");
                        });

                    b.OwnsOne("EquipmentMonitoring.Domain.ValueObjects.MeasurementUnit", "MeasurementUnit", b1 =>
                        {
                            b1.Property<Guid>("VariableId")
                                .HasColumnType("uuid");

                            b1.HasKey("VariableId");

                            b1.ToTable("Variables");

                            b1.WithOwner()
                                .HasForeignKey("VariableId");
                        });

                    b.Navigation("MeasurementUnit")
                        .IsRequired();

                    b.Navigation("ValueNode")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.HMI", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.AutomationDevice", null)
                        .WithOne()
                        .HasForeignKey("EquipmentMonitoring.Domain.Entities.HMI", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EquipmentMonitoring.Domain.ValueObjects.CommunicationNode", "UserNode", b1 =>
                        {
                            b1.Property<Guid>("HMIId")
                                .HasColumnType("uuid");

                            b1.HasKey("HMIId");

                            b1.ToTable("HMIs");

                            b1.WithOwner()
                                .HasForeignKey("HMIId");
                        });

                    b.Navigation("UserNode")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.PLC", b =>
                {
                    b.HasOne("EquipmentMonitoring.Domain.Entities.AutomationDevice", null)
                        .WithOne()
                        .HasForeignKey("EquipmentMonitoring.Domain.Entities.PLC", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonitoring.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
