<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\Units\DeleteUnit\" />
    <Folder Include="Commands\Units\AddAutomationDeviceToUnit\" />
    <Folder Include="Commands\Units\RemoveAutomationDeviceFromUnit\" />
    <Folder Include="Commands\Units\UpdateUnit\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentMonitoring.Contracts\EquipmentMonitoring.Contracts.csproj" />
    <ProjectReference Include="..\EquipmentMonitoring.Domain\EquipmentMonitoring.Domain.csproj" />
  </ItemGroup>

</Project>
