<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentMonitoring.Application\EquipmentMonitoring.Application.csproj" />
    <ProjectReference Include="..\EquipmentMonitoring.Domain\EquipmentMonitoring.Domain.csproj" />
    <ProjectReference Include="..\EquipmentMonitoring.GrpcProtos\EquipmentMonitoring.GrpcProtos.csproj" />
    <ProjectReference Include="..\EquipmentMonitoring.Persistence\EquipmentMonitoring.Persistence.csproj" />
  </ItemGroup>

</Project>
